export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const SET_LOADING_STATUS_LIST = 'SET_LOADING_LIST';
export const DELETE_PRODUCT_FROM_LIST = 'DELETE_PRODUCT_FROM_LIST';
export const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST';
export const SET_ERROR_LABEL_LIST = 'SET_ERROR_LABEL_LIST';

export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_LOADING_STATUS_DETAILS = 'SET_LOADING_DETAILS';
export const OPEN_MODAL_DETAILS = 'OPEN_MODAL_DETAILS';
export const CLOSE_MODAL_DETAILS = 'CLOSE_MODAL_DETAILS';

export const SET_LOADING_STATUS_CART = 'SET_LOADING_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const MODIFY_PRODUCT_QUANTITY = 'MODIFY_PRODUCT_QUANTITY';
export const UPDATE_PRODUCT_CART = 'UPDATE_PRODUCT_CART';

export const SET_EDITABLE_PRODUCT = 'SET_EDITABLE_PRODUCT';
export const CHANGE_PRODUCT_NAME = 'MODIFY_PRODUCT_NAME';
export const CHANGE_PRODUCT_CATEGORY = 'CHANGE_PRODUCT_CATEGORY';
export const CHANGE_PRODUCT_PRICE = 'CHANGE_PRODUCT_PRICE';
export const CHANGE_PRODUCT_IMAGE = 'CHANGE_PRODUCT_IMAGE';
export const CHANGE_PRODUCT_DESCRIPTION = 'CHANGE_PRODUCT_DESCRIPTION';
export const SET_LOADING_STATUS_EDITABLE = 'SET_LOADING_STATUS_EDITABLE';